"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_latte"

format = """
[░▒▓](lavender)\
[  ](bg:lavender fg:crust)\
[](bg:lavender fg:base)\
$directory\
([](fg:base bg:lavender)\
$git_branch\
$git_status)\
[](fg:base bg:lavender)\
$time\
[](fg:lavender)\
$fill\
[](fg:mauve)\
[$bun\
$c\
$cmake\
$cobol\
$cpp\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$gleam\
$golang\
$gradle\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$maven\
$mojo\
$nim\
$nodejs\
$ocaml\
$odin\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$xmake\
$zig\
$aws\
$gcloud\
$openstack\
$azure\
$docker_context\
$kubernetes](bg:mauve)\
([](fg:crust bg:mauve)\
$cmd_duration)\
[](fg:mauve)
$character"""

[directory]
style = "fg:crust bg:lavender"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol $branch ](fg:crust bg:lavender)]($style)'

[git_status]
style = "bg:lavender"
format = '[[($all_status$ahead_behind )](fg:crust bg:lavender)]($style)'

[time]
disabled = false
time_format = "%T"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'

[fill]
symbol = "-"
style = "subtext0"

[cmd_duration]
style = "bg:mauve"
format = '[[  $duration ](fg:crust bg:mauve)]($style)'

[bun]
format = '[$symbol($version )](bold red bg:mauve)'

[c]
format = '[$symbol($version(-$name) )](bold 149 bg:mauve)'

[cmake]
format = '[$symbol($version )](fg:crust bg:mauve)'

[cobol]
format = '[$symbol($version )](fg:crust bg:mauve)'

[cpp]
format = '[$symbol($version(-$name) )](bold 149 bg:mauve)'

[daml]
format = '[$symbol($version )](bold cyan bg:mauve)'

[dart]
format = '[$symbol($version )](fg:crust bg:mauve)'

[deno]
format = '[$symbol($version )](green bold bg:mauve)'

[dotnet]
format = '[$symbol($version )(🎯 $tfm )](fg:crust bg:mauve)'

[elixir]
format = '[$symbol($version (OTP $otp_version) )](fg:crust bg:mauve)'

[elm]
format = '[$symbol($version )](cyan bold bg:mauve)'

[erlang]
format = '[$symbol($version )](bold red bg:mauve)'

[fennel]
format = '[$symbol($version )](bold green bg:mauve)'

[fortran]
format = '[$symbol($version )](fg:crust bg:mauve)'

[gleam]
format = '[$symbol($version )](bold #FFAFF3 bg:mauve)'

[golang]
format = '[$symbol($version )](bold cyan bg:mauve)'

[gradle]
format = '[$symbol($version )](bold bright-cyan bg:mauve)'

[haskell]
format = '[$symbol($version )](fg:crust bg:mauve)'

[haxe]
format = '[$symbol($version )](bold fg:202 bg:mauve)'

[helm]
format = '[$symbol($version )](bold white bg:mauve)'

[java]
format = '[${symbol}(${version} )](red dimmed bg:mauve)'

[julia]
format = '[$symbol($version )](fg:crust bg:mauve)'

[kotlin]
format = '[$symbol($version )](fg:crust bg:mauve)'

[lua]
format = '[$symbol($version )](fg:crust bg:mauve)'

[maven]
format = '[$symbol($version )](fg:crust bg:mauve)'

[mojo]
format = '[$symbol($version )](bold orange bg:mauve)'

[nim]
format = '[$symbol($version )](bold yellow bg:mauve)'

[nodejs]
format = '[$symbol($version )](bold green bg:mauve)'

[ocaml]
format = '[$symbol($version )](bold yellow bg:mauve)'

[odin]
format = '[$symbol($version )](bold green bg:mauve)'

[opa]
format = '[$symbol($version )](fg:crust bg:mauve)'

[perl]
format = '[$symbol($version )](fg:crust bg:mauve)'

[php]
format = '[$symbol($version )](fg:crust bg:mauve)'

[pulumi]
format = '[$symbol$stack](fg:crust bg:mauve) '

[purescript]
format = '[$symbol($version )](bold white bg:mauve)'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )](yellow bold bg:mauve)'

[quarto]
format = '[$symbol($version )](fg:crust bg:mauve)'

[raku]
format = '[$symbol($version )](bold 149 bg:mauve)'

[rlang]
format = '[$symbol($version )](fg:crust bg:mauve)'

[red]
format = '[$symbol($version )](bold red bg:mauve)'

[ruby]
format = '[$symbol($version )](bold red bg:mauve)'

[rust]
format = '[$symbol($version )](bold red bg:mauve)'

[scala]
format = '[$symbol($version )](bold red bg:mauve)'

[solidity]
format = '[$symbol($version )](fg:crust bg:mauve)'

[swift]
format = '[$symbol($version )](bold 202 bg:mauve)'

[terraform]
format = '[$symbol$workspace](fg:crust bg:mauve) '

[typst]
format = '[$symbol($version )](fg:crust bg:mauve)'

[vlang]
format = '[$symbol($version )](fg:crust bg:mauve)'

[vagrant]
format = '[$symbol($version )](fg:crust bg:mauve)'

[xmake]
format = '[$symbol($version )](fg:crust bg:mauve)'

[zig]
format = '[$symbol($version )](bold yellow bg:mauve)'

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\] )](bold yellow bg:mauve)'

[gcloud]
format = '[$symbol$account(@$domain)(\($region\))](fg:crust bg:mauve) '

[openstack]
format = '[$symbol$cloud(\($project\))](fg:crust bg:mauve) '

[azure]
format = '[$symbol($subscription)](fg:crust bg:mauve) '

[docker_context]
format = '[$symbol$context](fg:crust bg:mauve) '

[kubernetes]
format = '[$symbol$context( \($namespace\))](fg:crust bg:mauve) '

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
